### ISSUE TITLE
Bug: Airtable extension fails to load when user is rate limited

### ISSUE THREAD

**Issue by ClemRSYB** [BaseQL/baseql-docs#12]
Hello support!
It seems I am unable to use the extension in Airtable at the moment. None of the direct queries are working and opening the extension results in a never-ending loading page.
The table we are working with is https://airtable.com/appGbUtR8glJMNBrU/tbljJmxWTyVCLMENg/viwedu77eiqJc58kg?blocks=biply64iKJs2wEjQl

Your status page seem to indicate that everything is fine, so I don't know if it's localised?

Thanks in advance,

Clémence Rigolet

**Comment by djseeds** [comment]
Hello @ClemRSYB!

Apologies for the delay, it looks like the automated upgrade process didn't fully complete so I've gone ahead and completed the process for your account manually. Please let us know if this has solved the issue.

**Comment by ClemRSYB** [comment]
Edit: This was due to us being rate limited. It would have been nice to have this as a more apparent message instead of just the loading page!

**Comment by djseeds** [comment]
Great feedback, thanks! We will look into this bug to ensure there's a useful message to highlight the rate limit.

**Comment by djseeds** [comment]
I've pushed an update both to our app and Airtable extension to add a useful error message. The update is live in our app now, and the Airtable extension should be updated in the next ~week or so.

Thanks again for the report!
